services:
  backend:
    build:
      context: ./TransportApp/Backend/TransportManagement.API
      dockerfile: Dockerfile
    ports:
      - "5024:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always

  frontend:
    build:
      context: ./TransportApp/Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=https://api.rmconsultingsrv.com/api # Cambiar por tu URL de API real
    restart: always
